version: '3.4'

services:

  #Infrastructure Containers

    # uncomment the following to enable container based SQL server (repeat in the docker-compose.override.yml)
    # to connect via SSMS connect to 127.0.0.1,8010
    # to browse container host file system:
    #   docker exec -it [docker image id] bash
     # to restore data copy backups to the container using the following command to copy the backup files:
    #   docker cp [local file path] [docker image id]:/var/opt/mssql/data
    # uncomment all appsettings.json files that contain connection strings
    # future revisions will automatically restore databases if the backups are present
    #sql.data:
    #  image: microsoft/mssql-server-linux:2017-latest

    # uncomment the follow to enable container based postgres server (repeat in the docker-compose.override.yml)
    # to connect via pgadmin connect to tcp:127.0.0.1; port:8011
    #postgres.data:
    #  image: postgres:alpine

  #API Containers
    catalog.api:
      image: ${DOCKER_REGISTRY-}catalogapi
      build:
        context: .
        dockerfile: src/Services/Catalog/Catalog.API/Catalog.API/Dockerfile
      depends_on:
        - identity.api

    masterdata.api:
      image: ${DOCKER_REGISTRY-}masterdataapi
      build:
        context: .
        dockerfile: src/Services/MasterData/MasterData.API/MasterData.API/Dockerfile
      depends_on:
       - identity.api

    identity.api:
      image: ${DOCKER_REGISTRY-}identityapi
      build:
        context: .
        dockerfile: src/Services/Identity/Identity.API/Dockerfile

  #API gateways
    pricingsimulationapigw:
      image: ${DOCKER_REGISTRY-}ocelotapigw
      build:
        context: .
        dockerfile: src/ApiGateways/ApiGatewayBase/OcelotApiGw/Dockerfile
      depends_on:
        - catalog.api
        - masterdata.api

  #WebApps
    pricingsimulation.spa:
      image: ${DOCKER_REGISTRY-}pricingsimulationspa
      build:
        context: .
        dockerfile: src/Web/PricingSimulation/PricingSimulation.SPA/Dockerfile
      depends_on: 
        - catalog.api
        - masterdata.api
        - pricingsimulationapigw